# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67dc685f1215cb3757b82b9f7d1cd59442fc9cb6cd351f6562d2a7adbaed334958d113fc10caa1acbccbbdc0d39d5e09c4a3a2f761d4e7dc8b5f72c14985e9f5

test:
  secret_key_base: 1e9dc4f91edf7a4e4e713208302d6a5bc3f2994de38110b8359d8defe53e1de69c3607c1f0cb7e3d3e3260cb1e73eeee03131f50574c1efc97b45b6f967e0bc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
